# No arquivo .gql(GraphQL) é aonde definimos nossos objetos(types) que posteriomente 
# irá ser implementado a logica no documento resolvers.js
# nesse arquivo schema definimos os objetos que difinem as disciplinas
enum NomeDisciplina {
    PI
    BD
    ALG
    TI
    ARQUICOMP
}

type Disciplina {
    id: Int
    nome: NomeDisciplina
    cargaHoraria: Int
}

type Query {
    disciplinas: [Disciplina]
}